### ISSUE TITLE
Area selection should use two distinct actions for the corners

### ISSUE THREAD

**Issue by Firigion** [Ghoulboy78/World-edit-scarpet#12]
Currently, the area selection is done via
```python
__on_player_swings_hand(player, hand) ->
(
    if(player~'holds':0==global_wand,
        if (global_selection && length(global_selection)>1, clear_selection() );
        if (!global_selection, _set_start_point(player), _set_end_point(player) );
    )
);
```
but this means that when making a selection, if the user misclicks the second corner, they have to fly back to the first position to set it again. Having two distinct actions for each corner makes it easier to make the selections.

We currently have four actions at our disposal: right and left click while sneaking or not seneaking. Do we need to save them for some use, or should they me used mainly for area selection (and maybe movement?).

**Comment by Firigion** [comment]
Alternative: right click sets the corners, lef click grabs a corner, in case the user wants to set that one corner again. Detecting the left click on the corner is a bit cumbersome, since the armour stands ar markers and have no hitbox, but it's an idea.

Another idea is using sift left click to move the selection forward, shift right click to move it back and maybe even move the corners if we do implement selecting them. Of course any combination of these is usable: right click and shift right click to set corners, left and whift left to move, whatever.

**Comment by BisUmTo** [comment]
Since many players already know the WorldEdit/Litematica selection input, I think it would be a nice idea to keep this method aviable via config anyway.

**Comment by gnembon** [comment]
agree that breaking the selection should be harder to do, rather than easier to do. 
I like the use of rightclicking of the element as operation to grab it, and left click to set it. The reason I used marker armorstands is because their sticks are not glowing, but selection of 'points' in the canvas should be possible. We can do that by projecting the look to 4 blocks in front and grabbing the closest hook within lets say 3-4 blocks.

we will need to have some 'markers' in the canvas area anyways, since having things like this would be really nice to have
https://www.youtube.com/watch?v=igmKphb7B2A

**Comment by gnembon** [comment]
how selection is done in WE/LM? @BisUmTo

**Comment by BisUmTo** [comment]
**Common inputs:**
Left click -> Pos1 -> first corner of a cuboid selection
Right click -> Pos2 -> second corner of a cuboid selection

**Litematica only inputs:**
You can select a corner and use the scroll weal to move the selected corner in the direction you're looking (if scrolled up) or in the reverse direction (if scrolled down)

**Comment by Ghoulboy78** [comment]
done ig
